### ISSUE TITLE
Include Django 4.2 with Python 3.11

### ISSUE THREAD

**Issue by nickmoreton** [nimasmi/django-gov-notify#13]
The latest version 0.5.0 can be installed on:

- Python 3.8
- Django 4.2

It's not possible to install the latest version when upgrading to python 3.11

- Python 3.11
- Django 4.2

The result is:
```
Because django-gov-notify (0.5.0) depends on django (>=5.0)
 and no versions of django-gov-notify match >0.5.0,<0.6.0, django-gov-notify (>=0.5.0,<0.6.0) requires django (>=5.0).
So, because bc depends on both Django (~4.2) and django-gov-notify (^0.5.0), version solving failed.
```

Do you need to alter https://github.com/nimasmi/django-gov-notify/blob/ad8376805ab49a2ff0fc744dbbc22fab70046084/pyproject.toml#L30

```
django = [
    {version = ">=3.2", python = ">=3.8,<3.10"},
    {version = ">=4.2", python = ">=3.8,<3.12"},
    {version = ">=5.0", python = ">=3.10,<3.12"},
]
```

https://docs.djangoproject.com/en/5.0/faq/install/#what-python-version-can-i-use-with-django

**Comment by alxbridge** [comment]
I believe the problem here relates to this `poetry` issue: https://github.com/python-poetry/poetry/issues/707

Poetry's resolver looks at the Django versions specified in this package's _pyproject.toml_ and tries to resolve the dependencies **only** for the most up-to-date version listed for the version of Python in use.

So for a Django project where the version of Python used is >=3.10, this means Poetry will only try to resolve dependencies for this package with Django 5.0. If the project is using Django 4.2 with Python >=3.10 - as with this issue report - the resolver will fail because it thinks 5.0 is required.

Until the Poetry issue is addressed, I think the only solution for this package is to relax the version specification.
